### ISSUE TITLE
failed to fetch item values from rolimons

### ISSUE THREAD

**Issue by qsels** [mxmmxx/quaid#1]
I keep getting an error for getting item values from rolimons.
![image](https://user-images.githubusercontent.com/67203605/189471028-9bd3275f-d514-47e2-a111-d9faae4f3243.png)

**Comment by mxmmxx** [comment]
this isn't an issue, this is for code reference only.
i've removed a few parts of the whitelist and as you don't have a legitimate whitelist you can't connect to my server.
