### ISSUE TITLE
need help with proxies

### ISSUE THREAD

**Issue by MeekTortoise** [mxmmxx/quaid#4]
what do i need to fill in the proxies.txt? pls help

**Comment by mxmmxx** [comment]
this is just for code reference, not use 😃😃

**Comment by MeekTortoise** [comment]
But then it gives an error: make sure you are connected to the internet and make sure your proxies are right

**Comment by mxmmxx** [comment]
this doesn't include the info for you to whitelist yourself, this is just for code reference again.
